### ISSUE TITLE
Update gems

### ISSUE THREAD

**Issue by sergey-alekseev** [ASoftCo/shopify-app-starter-kit#1]
First of all to fix known vulnerabilities:  
![screen shot 2018-03-30 at 1 10 02 pm](https://user-images.githubusercontent.com/2371639/38134457-c610d3bc-341b-11e8-9115-6bf3866c7c38.png)

**Comment by staniel359** [comment]
@sergey-alekseev Done.

**Comment by sergey-alekseev** [comment]
One more now:  
![screen shot 2018-06-21 at 5 11 36 pm](https://user-images.githubusercontent.com/2371639/41724510-5fa38786-7576-11e8-8b69-7c6845c0e790.png)
![screen shot 2018-06-21 at 5 11 51 pm](https://user-images.githubusercontent.com/2371639/41724512-5fc2cd8a-7576-11e8-922e-3cb4f5383433.png)
