### ISSUE TITLE
Possible Documentation Update

### ISSUE THREAD

**Issue by pjatx** [ASoftCo/shopify-app-starter-kit#2]
Hey! First of all thanks for putting this together. It's great. I was setting up this up locally and noticed a possible typo on item #13

13. Change an application host name in the `config/settings/*.rb` files

After cloning the repo, I see .yml files vs .rb files so just wanted to call that out in case it wasn't intentional. If it was and I'm misreading the documentation, my apologies - feel free to close this issue. 

![image](https://user-images.githubusercontent.com/5004634/41540681-49d29ba6-72d6-11e8-8502-89e5ca7993bd.png)

**Comment by dhalai** [comment]
Hey @pjatx , thanks for your notice. 👍  You're right, it should be `yml` extension instead of `rb`. We've updated the `README` file. 

JFYI, Shopify improved their tools (Polaris, GraphQL, etc..) and we're going to update the repo soon.
Anyway, feel free to ask anything

**Comment by pjatx** [comment]
@dhalai Thanks! First time trying to build one - honestly just needing to get access to more advanced shipping rate logic. Will track progress on this repo

**Comment by dhalai** [comment]
@pjatx Did you check [CarrierService](https://help.shopify.com/api/reference/shipping_and_fulfillment/carrierservice)? I think it should be useful for you.

I'll close the issue, just open a new one if it's necessary

**Comment by pjatx** [comment]
@dhalai Yeah, that's the path I'm going down - thanks! Will do.

**Comment by pjatx** [comment]
@dhalai So - just started setting up my app this afternoon and have a couple of questions: 
* Noticing that the `config/initializers/shopify_app.rb` isn't using the environmental variables. Is that intentional? 
* Can't seem to get OAuth to work - getting the following error message when installing in a dev store: `Oauth error invalid_request: The authorization code was not found or was already used`

**Comment by pjatx** [comment]
I think there were a few issues with the current code with v8 of the Shopify App Gem. I'll open a quick PR of what solved it for me (minus the env variables issue I mentioned above)

**Comment by dhalai** [comment]
Hey @pjatx. 
> Noticing that the config/initializers/shopify_app.rb isn't using the environmental variables. Is that intentional?  

Yep, it's better to use encrypted data here. As I said above, we'll update the repo soon. The new version will be using rails 5.2 with encrypted secrets.
> Can't seem to get OAuth to work  

Hm.. it's strange. Anyway, if you already resolved the problem, we'd be happy to see a PR

**Comment by pjatx** [comment]
@dhalai Done! Did what worked for me at least. I think calling out the need to manually add scopes and credentials to the shopify_app initializer would be helpful as well.

**Comment by dhalai** [comment]
Thanks @pjatx. Sure, we'll update it soon

**Comment by dhalai** [comment]
Hi @pjatx! FYI, we updated the `starter-kit` and documentation.
